<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dell-PC" failures="1" tests="6" name="TestNGSessions.AmazonTestBT" time="4.202" errors="0" timestamp="25 Nov 2021 13:28:04 GMT" skipped="3">
  <testcase classname="TestNGSessions.AmazonTestBT" name="amazonLogoTest" time="1.539"/>
  <testcase classname="TestNGSessions.AmazonTestBT" name="amazonTitleTest" time="0.019"/>
  <testcase classname="TestNGSessions.AmazonTestBT" name="amaonFooterLinksCountTest" time="2.644">
    <failure message="expected [21] but found [22]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [21] but found [22]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at TestNGSessions.AmazonTestBT.amaonFooterLinksCountTest(AmazonTestBT.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- amaonFooterLinksCountTest -->
  <testcase classname="TestNGSessions.AmazonTestBT" name="amazonTest6">
    <skipped/>
  </testcase> <!-- amazonTest6 -->
  <testcase classname="TestNGSessions.AmazonTestBT" name="amazonTest5">
    <skipped/>
  </testcase> <!-- amazonTest5 -->
  <testcase classname="TestNGSessions.AmazonTestBT" name="amazonTest4">
    <skipped/>
  </testcase> <!-- amazonTest4 -->
</testsuite> <!-- TestNGSessions.AmazonTestBT -->
